// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CdnProvidedCertificateWithoutOrg cdn provided certificate without org
//
// swagger:model CdnProvidedCertificateWithoutOrg
type CdnProvidedCertificateWithoutOrg struct {

	// at id
	AtID string `json:"@id,omitempty"`

	// at type
	AtType string `json:"@type,omitempty"`

	// auto renew
	AutoRenew bool `json:"auto_renew,omitempty"`

	// certificate authority
	// Enum: [DigiCert LetsEncrypt]
	CertificateAuthority string `json:"certificate_authority,omitempty"`

	// certificate label
	CertificateLabel string `json:"certificate_label,omitempty"`

	// created
	// Format: date-time
	Created strfmt.DateTime `json:"created,omitempty"`

	// created by
	CreatedBy *Actor `json:"created_by,omitempty"`

	// dcv method
	// Enum: [Email DnsCnameToken DnsTxtToken]
	DcvMethod string `json:"dcv_method,omitempty"`

	// deployments
	Deployments []*RequestDeployment `json:"deployments"`

	// description
	Description string `json:"description,omitempty"`

	// domains
	Domains []*Domain `json:"domains"`

	// expiration date
	// Format: date-time
	ExpirationDate strfmt.DateTime `json:"expiration_date,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// last modified
	// Format: date-time
	LastModified strfmt.DateTime `json:"last_modified,omitempty"`

	// modified by
	ModifiedBy *Actor `json:"modified_by,omitempty"`

	// request type
	// Enum: [Basic Enterprise Custom AzureCustom]
	RequestType string `json:"request_type,omitempty"`

	// thumbprint
	Thumbprint string `json:"thumbprint,omitempty"`

	// validation type
	// Enum: [None DV OV EV]
	ValidationType string `json:"validation_type,omitempty"`

	// workflow error message
	WorkflowErrorMessage string `json:"workflow_error_message,omitempty"`
}

// Validate validates this cdn provided certificate without org
func (m *CdnProvidedCertificateWithoutOrg) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCertificateAuthority(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedBy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDcvMethod(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeployments(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDomains(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExpirationDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastModified(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateModifiedBy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequestType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValidationType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var cdnProvidedCertificateWithoutOrgTypeCertificateAuthorityPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["DigiCert","LetsEncrypt"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		cdnProvidedCertificateWithoutOrgTypeCertificateAuthorityPropEnum = append(cdnProvidedCertificateWithoutOrgTypeCertificateAuthorityPropEnum, v)
	}
}

const (

	// CdnProvidedCertificateWithoutOrgCertificateAuthorityDigiCert captures enum value "DigiCert"
	CdnProvidedCertificateWithoutOrgCertificateAuthorityDigiCert string = "DigiCert"

	// CdnProvidedCertificateWithoutOrgCertificateAuthorityLetsEncrypt captures enum value "LetsEncrypt"
	CdnProvidedCertificateWithoutOrgCertificateAuthorityLetsEncrypt string = "LetsEncrypt"
)

// prop value enum
func (m *CdnProvidedCertificateWithoutOrg) validateCertificateAuthorityEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, cdnProvidedCertificateWithoutOrgTypeCertificateAuthorityPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CdnProvidedCertificateWithoutOrg) validateCertificateAuthority(formats strfmt.Registry) error {
	if swag.IsZero(m.CertificateAuthority) { // not required
		return nil
	}

	// value enum
	if err := m.validateCertificateAuthorityEnum("certificate_authority", "body", m.CertificateAuthority); err != nil {
		return err
	}

	return nil
}

func (m *CdnProvidedCertificateWithoutOrg) validateCreated(formats strfmt.Registry) error {
	if swag.IsZero(m.Created) { // not required
		return nil
	}

	if err := validate.FormatOf("created", "body", "date-time", m.Created.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *CdnProvidedCertificateWithoutOrg) validateCreatedBy(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedBy) { // not required
		return nil
	}

	if m.CreatedBy != nil {
		if err := m.CreatedBy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("created_by")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("created_by")
			}
			return err
		}
	}

	return nil
}

var cdnProvidedCertificateWithoutOrgTypeDcvMethodPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Email","DnsCnameToken","DnsTxtToken"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		cdnProvidedCertificateWithoutOrgTypeDcvMethodPropEnum = append(cdnProvidedCertificateWithoutOrgTypeDcvMethodPropEnum, v)
	}
}

const (

	// CdnProvidedCertificateWithoutOrgDcvMethodEmail captures enum value "Email"
	CdnProvidedCertificateWithoutOrgDcvMethodEmail string = "Email"

	// CdnProvidedCertificateWithoutOrgDcvMethodDNSCnameToken captures enum value "DnsCnameToken"
	CdnProvidedCertificateWithoutOrgDcvMethodDNSCnameToken string = "DnsCnameToken"

	// CdnProvidedCertificateWithoutOrgDcvMethodDNSTxtToken captures enum value "DnsTxtToken"
	CdnProvidedCertificateWithoutOrgDcvMethodDNSTxtToken string = "DnsTxtToken"
)

// prop value enum
func (m *CdnProvidedCertificateWithoutOrg) validateDcvMethodEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, cdnProvidedCertificateWithoutOrgTypeDcvMethodPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CdnProvidedCertificateWithoutOrg) validateDcvMethod(formats strfmt.Registry) error {
	if swag.IsZero(m.DcvMethod) { // not required
		return nil
	}

	// value enum
	if err := m.validateDcvMethodEnum("dcv_method", "body", m.DcvMethod); err != nil {
		return err
	}

	return nil
}

func (m *CdnProvidedCertificateWithoutOrg) validateDeployments(formats strfmt.Registry) error {
	if swag.IsZero(m.Deployments) { // not required
		return nil
	}

	for i := 0; i < len(m.Deployments); i++ {
		if swag.IsZero(m.Deployments[i]) { // not required
			continue
		}

		if m.Deployments[i] != nil {
			if err := m.Deployments[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deployments" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("deployments" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CdnProvidedCertificateWithoutOrg) validateDomains(formats strfmt.Registry) error {
	if swag.IsZero(m.Domains) { // not required
		return nil
	}

	for i := 0; i < len(m.Domains); i++ {
		if swag.IsZero(m.Domains[i]) { // not required
			continue
		}

		if m.Domains[i] != nil {
			if err := m.Domains[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("domains" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("domains" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CdnProvidedCertificateWithoutOrg) validateExpirationDate(formats strfmt.Registry) error {
	if swag.IsZero(m.ExpirationDate) { // not required
		return nil
	}

	if err := validate.FormatOf("expiration_date", "body", "date-time", m.ExpirationDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *CdnProvidedCertificateWithoutOrg) validateLastModified(formats strfmt.Registry) error {
	if swag.IsZero(m.LastModified) { // not required
		return nil
	}

	if err := validate.FormatOf("last_modified", "body", "date-time", m.LastModified.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *CdnProvidedCertificateWithoutOrg) validateModifiedBy(formats strfmt.Registry) error {
	if swag.IsZero(m.ModifiedBy) { // not required
		return nil
	}

	if m.ModifiedBy != nil {
		if err := m.ModifiedBy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("modified_by")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("modified_by")
			}
			return err
		}
	}

	return nil
}

var cdnProvidedCertificateWithoutOrgTypeRequestTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Basic","Enterprise","Custom","AzureCustom"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		cdnProvidedCertificateWithoutOrgTypeRequestTypePropEnum = append(cdnProvidedCertificateWithoutOrgTypeRequestTypePropEnum, v)
	}
}

const (

	// CdnProvidedCertificateWithoutOrgRequestTypeBasic captures enum value "Basic"
	CdnProvidedCertificateWithoutOrgRequestTypeBasic string = "Basic"

	// CdnProvidedCertificateWithoutOrgRequestTypeEnterprise captures enum value "Enterprise"
	CdnProvidedCertificateWithoutOrgRequestTypeEnterprise string = "Enterprise"

	// CdnProvidedCertificateWithoutOrgRequestTypeCustom captures enum value "Custom"
	CdnProvidedCertificateWithoutOrgRequestTypeCustom string = "Custom"

	// CdnProvidedCertificateWithoutOrgRequestTypeAzureCustom captures enum value "AzureCustom"
	CdnProvidedCertificateWithoutOrgRequestTypeAzureCustom string = "AzureCustom"
)

// prop value enum
func (m *CdnProvidedCertificateWithoutOrg) validateRequestTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, cdnProvidedCertificateWithoutOrgTypeRequestTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CdnProvidedCertificateWithoutOrg) validateRequestType(formats strfmt.Registry) error {
	if swag.IsZero(m.RequestType) { // not required
		return nil
	}

	// value enum
	if err := m.validateRequestTypeEnum("request_type", "body", m.RequestType); err != nil {
		return err
	}

	return nil
}

var cdnProvidedCertificateWithoutOrgTypeValidationTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["None","DV","OV","EV"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		cdnProvidedCertificateWithoutOrgTypeValidationTypePropEnum = append(cdnProvidedCertificateWithoutOrgTypeValidationTypePropEnum, v)
	}
}

const (

	// CdnProvidedCertificateWithoutOrgValidationTypeNone captures enum value "None"
	CdnProvidedCertificateWithoutOrgValidationTypeNone string = "None"

	// CdnProvidedCertificateWithoutOrgValidationTypeDV captures enum value "DV"
	CdnProvidedCertificateWithoutOrgValidationTypeDV string = "DV"

	// CdnProvidedCertificateWithoutOrgValidationTypeOV captures enum value "OV"
	CdnProvidedCertificateWithoutOrgValidationTypeOV string = "OV"

	// CdnProvidedCertificateWithoutOrgValidationTypeEV captures enum value "EV"
	CdnProvidedCertificateWithoutOrgValidationTypeEV string = "EV"
)

// prop value enum
func (m *CdnProvidedCertificateWithoutOrg) validateValidationTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, cdnProvidedCertificateWithoutOrgTypeValidationTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CdnProvidedCertificateWithoutOrg) validateValidationType(formats strfmt.Registry) error {
	if swag.IsZero(m.ValidationType) { // not required
		return nil
	}

	// value enum
	if err := m.validateValidationTypeEnum("validation_type", "body", m.ValidationType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this cdn provided certificate without org based on the context it is used
func (m *CdnProvidedCertificateWithoutOrg) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCreatedBy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDeployments(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDomains(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateModifiedBy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CdnProvidedCertificateWithoutOrg) contextValidateCreatedBy(ctx context.Context, formats strfmt.Registry) error {

	if m.CreatedBy != nil {
		if err := m.CreatedBy.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("created_by")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("created_by")
			}
			return err
		}
	}

	return nil
}

func (m *CdnProvidedCertificateWithoutOrg) contextValidateDeployments(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Deployments); i++ {

		if m.Deployments[i] != nil {
			if err := m.Deployments[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("deployments" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("deployments" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CdnProvidedCertificateWithoutOrg) contextValidateDomains(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Domains); i++ {

		if m.Domains[i] != nil {
			if err := m.Domains[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("domains" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("domains" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *CdnProvidedCertificateWithoutOrg) contextValidateModifiedBy(ctx context.Context, formats strfmt.Registry) error {

	if m.ModifiedBy != nil {
		if err := m.ModifiedBy.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("modified_by")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("modified_by")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CdnProvidedCertificateWithoutOrg) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CdnProvidedCertificateWithoutOrg) UnmarshalBinary(b []byte) error {
	var res CdnProvidedCertificateWithoutOrg
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
