// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CountryCode country code
//
// swagger:model CountryCode
type CountryCode struct {

	// country
	Country string `json:"country,omitempty"`

	// two letter code
	TwoLetterCode string `json:"two_letter_code,omitempty"`
}

// Validate validates this country code
func (m *CountryCode) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this country code based on context it is used
func (m *CountryCode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CountryCode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CountryCode) UnmarshalBinary(b []byte) error {
	var res CountryCode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
