// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DomainDcvFull domain dcv full
//
// swagger:model DomainDcvFull
type DomainDcvFull struct {

	// dcv method
	// Enum: [Email DnsCnameToken DnsTxtToken]
	DcvMethod string `json:"dcv_method,omitempty"`

	// dcv token
	DcvToken *DcvToken `json:"dcv_token,omitempty"`

	// domain id
	DomainID int64 `json:"domain_id,omitempty"`

	// emails
	Emails []string `json:"emails"`
}

// Validate validates this domain dcv full
func (m *DomainDcvFull) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDcvMethod(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDcvToken(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var domainDcvFullTypeDcvMethodPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Email","DnsCnameToken","DnsTxtToken"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		domainDcvFullTypeDcvMethodPropEnum = append(domainDcvFullTypeDcvMethodPropEnum, v)
	}
}

const (

	// DomainDcvFullDcvMethodEmail captures enum value "Email"
	DomainDcvFullDcvMethodEmail string = "Email"

	// DomainDcvFullDcvMethodDNSCnameToken captures enum value "DnsCnameToken"
	DomainDcvFullDcvMethodDNSCnameToken string = "DnsCnameToken"

	// DomainDcvFullDcvMethodDNSTxtToken captures enum value "DnsTxtToken"
	DomainDcvFullDcvMethodDNSTxtToken string = "DnsTxtToken"
)

// prop value enum
func (m *DomainDcvFull) validateDcvMethodEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, domainDcvFullTypeDcvMethodPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DomainDcvFull) validateDcvMethod(formats strfmt.Registry) error {
	if swag.IsZero(m.DcvMethod) { // not required
		return nil
	}

	// value enum
	if err := m.validateDcvMethodEnum("dcv_method", "body", m.DcvMethod); err != nil {
		return err
	}

	return nil
}

func (m *DomainDcvFull) validateDcvToken(formats strfmt.Registry) error {
	if swag.IsZero(m.DcvToken) { // not required
		return nil
	}

	if m.DcvToken != nil {
		if err := m.DcvToken.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dcv_token")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("dcv_token")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this domain dcv full based on the context it is used
func (m *DomainDcvFull) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDcvToken(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DomainDcvFull) contextValidateDcvToken(ctx context.Context, formats strfmt.Registry) error {

	if m.DcvToken != nil {
		if err := m.DcvToken.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dcv_token")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("dcv_token")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DomainDcvFull) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DomainDcvFull) UnmarshalBinary(b []byte) error {
	var res DomainDcvFull
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
