// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DomainCreateUpdate domain create update
//
// swagger:model DomainCreateUpdate
type Domain struct {

	// is common name
	IsCommonName bool `json:"is_common_name,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	ActiveDate strfmt.DateTime `json:"active_date,omitempty"`
	Created strfmt.DateTime `json:"created,omitempty"`
	ID int `json:"id"`
	Status string `json:"status,omitempty"`
}

// Validate validates this domain create update
func (m *Domain) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this domain create update based on context it is used
func (m *Domain) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Domain) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Domain) UnmarshalBinary(b []byte) error {
	var res Domain
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
