// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TaskItem task item
//
// swagger:model TaskItem
type TaskItem struct {

	// at id
	AtID string `json:"@id,omitempty"`

	// at type
	AtType string `json:"@type,omitempty"`

	// arguments
	Arguments interface{} `json:"arguments,omitempty"`

	// customer id
	CustomerID int32 `json:"customer_id,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// in date
	// Format: date-time
	InDate strfmt.DateTime `json:"in_date,omitempty"`

	// processed date
	// Format: date-time
	ProcessedDate strfmt.DateTime `json:"processed_date,omitempty"`

	// task type
	// Enum: [AssociateMediaType DisassociateMediaType ProcessDomainRootChange RevertSslMigration ProcessDeliveryRegionChange SslSharedMigration]
	TaskType string `json:"task_type,omitempty"`
}

// Validate validates this task item
func (m *TaskItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProcessedDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTaskType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TaskItem) validateInDate(formats strfmt.Registry) error {
	if swag.IsZero(m.InDate) { // not required
		return nil
	}

	if err := validate.FormatOf("in_date", "body", "date-time", m.InDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *TaskItem) validateProcessedDate(formats strfmt.Registry) error {
	if swag.IsZero(m.ProcessedDate) { // not required
		return nil
	}

	if err := validate.FormatOf("processed_date", "body", "date-time", m.ProcessedDate.String(), formats); err != nil {
		return err
	}

	return nil
}

var taskItemTypeTaskTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["AssociateMediaType","DisassociateMediaType","ProcessDomainRootChange","RevertSslMigration","ProcessDeliveryRegionChange","SslSharedMigration"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		taskItemTypeTaskTypePropEnum = append(taskItemTypeTaskTypePropEnum, v)
	}
}

const (

	// TaskItemTaskTypeAssociateMediaType captures enum value "AssociateMediaType"
	TaskItemTaskTypeAssociateMediaType string = "AssociateMediaType"

	// TaskItemTaskTypeDisassociateMediaType captures enum value "DisassociateMediaType"
	TaskItemTaskTypeDisassociateMediaType string = "DisassociateMediaType"

	// TaskItemTaskTypeProcessDomainRootChange captures enum value "ProcessDomainRootChange"
	TaskItemTaskTypeProcessDomainRootChange string = "ProcessDomainRootChange"

	// TaskItemTaskTypeRevertSslMigration captures enum value "RevertSslMigration"
	TaskItemTaskTypeRevertSslMigration string = "RevertSslMigration"

	// TaskItemTaskTypeProcessDeliveryRegionChange captures enum value "ProcessDeliveryRegionChange"
	TaskItemTaskTypeProcessDeliveryRegionChange string = "ProcessDeliveryRegionChange"

	// TaskItemTaskTypeSslSharedMigration captures enum value "SslSharedMigration"
	TaskItemTaskTypeSslSharedMigration string = "SslSharedMigration"
)

// prop value enum
func (m *TaskItem) validateTaskTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, taskItemTypeTaskTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *TaskItem) validateTaskType(formats strfmt.Registry) error {
	if swag.IsZero(m.TaskType) { // not required
		return nil
	}

	// value enum
	if err := m.validateTaskTypeEnum("task_type", "body", m.TaskType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this task item based on context it is used
func (m *TaskItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TaskItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaskItem) UnmarshalBinary(b []byte) error {
	var res TaskItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
