// Code generated by go-swagger; DO NOT EDIT.

package profiles_rl

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/EdgeCast/ec-sdk-go/edgecast/rtldmodels"
)

// ProfilesRateLimitingGetCustomerSettingsReader is a Reader for the ProfilesRateLimitingGetCustomerSettings structure.
type ProfilesRateLimitingGetCustomerSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProfilesRateLimitingGetCustomerSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProfilesRateLimitingGetCustomerSettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewProfilesRateLimitingGetCustomerSettingsOK creates a ProfilesRateLimitingGetCustomerSettingsOK with default headers values
func NewProfilesRateLimitingGetCustomerSettingsOK() *ProfilesRateLimitingGetCustomerSettingsOK {
	return &ProfilesRateLimitingGetCustomerSettingsOK{}
}

/* ProfilesRateLimitingGetCustomerSettingsOK describes a response with status code 200, with default header values.

Success
*/
type ProfilesRateLimitingGetCustomerSettingsOK struct {
	Payload *rtldmodels.HyperionCollectionRateLimitingProfileDto
}

func (o *ProfilesRateLimitingGetCustomerSettingsOK) Error() string {
	return fmt.Sprintf("[GET /v1.0/rl/profiles][%d] profilesRateLimitingGetCustomerSettingsOK  %+v", 200, o.Payload)
}
func (o *ProfilesRateLimitingGetCustomerSettingsOK) GetPayload() *rtldmodels.HyperionCollectionRateLimitingProfileDto {
	return o.Payload
}

func (o *ProfilesRateLimitingGetCustomerSettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rtldmodels.HyperionCollectionRateLimitingProfileDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
