// Code generated by go-swagger; DO NOT EDIT.

package lookups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/EdgeCast/ec-sdk-go/rtldmodels"
)

// LookupsGetStatusCodesReader is a Reader for the LookupsGetStatusCodes structure.
type LookupsGetStatusCodesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LookupsGetStatusCodesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLookupsGetStatusCodesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLookupsGetStatusCodesOK creates a LookupsGetStatusCodesOK with default headers values
func NewLookupsGetStatusCodesOK() *LookupsGetStatusCodesOK {
	return &LookupsGetStatusCodesOK{}
}

/* LookupsGetStatusCodesOK describes a response with status code 200, with default header values.

Success
*/
type LookupsGetStatusCodesOK struct {
	Payload *rtldmodels.HyperionCollectionCodeName
}

func (o *LookupsGetStatusCodesOK) Error() string {
	return fmt.Sprintf("[GET /v1.0/status-codes][%d] lookupsGetStatusCodesOK  %+v", 200, o.Payload)
}
func (o *LookupsGetStatusCodesOK) GetPayload() *rtldmodels.HyperionCollectionCodeName {
	return o.Payload
}

func (o *LookupsGetStatusCodesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rtldmodels.HyperionCollectionCodeName)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
