// Copyright 2022 Edgecast Inc., Licensed under the terms of the Apache 2.0
// license. See LICENSE file in project root for terms.

package appendix

import "github.com/EdgeCast/ec-sdk-go/edgecast/cps/models"

// This file was generated by codegen-sdk-go.
// Any changes made to this file may be overwritten.

// NewAppendixGetCertificateAuthoritiesOK creates a AppendixGetCertificateAuthoritiesOK with default headers values
func NewAppendixGetCertificateAuthoritiesOK() *AppendixGetCertificateAuthoritiesOK {
	return &AppendixGetCertificateAuthoritiesOK{}
}

/* AppendixGetCertificateAuthoritiesOK describes a response with status code 200, with default header values.

Success
*/
type AppendixGetCertificateAuthoritiesOK struct {
	models.AppendixCollection
}
