// Copyright 2022 Edgecast Inc., Licensed under the terms of the Apache 2.0
// license. See LICENSE file in project root for terms.

package appendix

import "github.com/EdgeCast/ec-sdk-go/edgecast/cps/models"

// This file was generated by codegen-sdk-go.
// Any changes made to this file may be overwritten.

// NewAppendixGetValidationStatusesOK creates a AppendixGetValidationStatusesOK with default headers values
func NewAppendixGetValidationStatusesOK() *AppendixGetValidationStatusesOK {
	return &AppendixGetValidationStatusesOK{}
}

/*
	AppendixGetValidationStatusesOK describes a response with status code 200, with default header values.

Success
*/
type AppendixGetValidationStatusesOK struct {
	models.HyperionCollectionNamedEntity
}
