// Code generated by go-swagger; DO NOT EDIT.

package rtldmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HyperionCollectionSystemDouble hyperion collection system double
//
// swagger:model HyperionCollection[System.Double]
type HyperionCollectionSystemDouble struct {

	// at id
	AtID string `json:"@id,omitempty"`

	// at type
	AtType *string `json:"@type,omitempty"`

	// items
	Items []float64 `json:"items"`

	// total items
	TotalItems int32 `json:"total_items,omitempty"`
}

// Validate validates this hyperion collection system double
func (m *HyperionCollectionSystemDouble) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hyperion collection system double based on context it is used
func (m *HyperionCollectionSystemDouble) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HyperionCollectionSystemDouble) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HyperionCollectionSystemDouble) UnmarshalBinary(b []byte) error {
	var res HyperionCollectionSystemDouble
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
