// Code generated by go-swagger; DO NOT EDIT.

package rtldmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RtldCustomItemDto rtld custom item dto
//
// swagger:model RtldCustomItemDto
type RtldCustomItemDto struct {

	// category
	Category string `json:"category,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this rtld custom item dto
func (m *RtldCustomItemDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this rtld custom item dto based on context it is used
func (m *RtldCustomItemDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RtldCustomItemDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RtldCustomItemDto) UnmarshalBinary(b []byte) error {
	var res RtldCustomItemDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
