// Code generated by go-swagger; DO NOT EDIT.

package rtldmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RtldSumoLogicSettingDto rtld sumo logic setting dto
//
// swagger:model RtldSumoLogicSettingDto
type RtldSumoLogicSettingDto struct {

	// masked url
	MaskedURL string `json:"masked_url,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this rtld sumo logic setting dto
func (m *RtldSumoLogicSettingDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this rtld sumo logic setting dto based on context it is used
func (m *RtldSumoLogicSettingDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RtldSumoLogicSettingDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RtldSumoLogicSettingDto) UnmarshalBinary(b []byte) error {
	var res RtldSumoLogicSettingDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
