// Code generated by go-swagger; DO NOT EDIT.

package rtldmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RtldAwsSettingDto rtld aws setting dto
//
// swagger:model RtldAwsSettingDto
type RtldAwsSettingDto struct {

	// bucket
	Bucket string `json:"bucket,omitempty"`

	// prefix
	Prefix string `json:"prefix,omitempty"`

	// region
	Region string `json:"region,omitempty"`
}

// Validate validates this rtld aws setting dto
func (m *RtldAwsSettingDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this rtld aws setting dto based on context it is used
func (m *RtldAwsSettingDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RtldAwsSettingDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RtldAwsSettingDto) UnmarshalBinary(b []byte) error {
	var res RtldAwsSettingDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
