// Code generated by go-swagger; DO NOT EDIT.

package rtldmodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WafProfileDto waf profile dto
//
// swagger:model WafProfileDto
type WafProfileDto struct {
	BaseProfileDto

	// filters
	Filters *RtldWafFiltersDto `json:"filters,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *WafProfileDto) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 BaseProfileDto
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}

	fmt.Printf("\nm: %v\n", m)

	m.BaseProfileDto = aO0

	// AO1
	var dataAO1 struct {
		Filters *RtldWafFiltersDto `json:"filters,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Filters = dataAO1.Filters

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m WafProfileDto) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.BaseProfileDto)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		Filters *RtldWafFiltersDto `json:"filters,omitempty"`
	}

	dataAO1.Filters = m.Filters

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this waf profile dto
func (m *WafProfileDto) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with BaseProfileDto
	if err := m.BaseProfileDto.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFilters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WafProfileDto) validateFilters(formats strfmt.Registry) error {

	if swag.IsZero(m.Filters) { // not required
		return nil
	}

	if m.Filters != nil {
		if err := m.Filters.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("filters")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("filters")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this waf profile dto based on the context it is used
func (m *WafProfileDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with BaseProfileDto
	if err := m.BaseProfileDto.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFilters(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WafProfileDto) contextValidateFilters(ctx context.Context, formats strfmt.Registry) error {

	if m.Filters != nil {
		if err := m.Filters.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("filters")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("filters")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WafProfileDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WafProfileDto) UnmarshalBinary(b []byte) error {
	var res WafProfileDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
