// Copyright 2022 Edgecast Inc., Licensed under the terms of the Apache 2.0
// license. See LICENSE file in project root for terms.

package certificate

// This file was generated by codegen-sdk-go.
// Any changes made to this file may be overwritten.

import (
	"github.com/EdgeCast/ec-sdk-go/edgecast/cps/models"
)

// NewCertificateCancelNoContent creates a CertificateCancelNoContent with default headers values
func NewCertificateCancelNoContent() *CertificateCancelNoContent {
	return &CertificateCancelNoContent{}
}

/* CertificateCancelNoContent describes a response with status code 204, with default header values.

Success
*/
type CertificateCancelNoContent struct {
}

// NewCertificateCancelBadRequest creates a CertificateCancelBadRequest with default headers values
func NewCertificateCancelBadRequest() *CertificateCancelBadRequest {
	return &CertificateCancelBadRequest{}
}

/* CertificateCancelBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CertificateCancelBadRequest struct {
	models.HyperionErrorReponse
}

// NewCertificateCancelNotFound creates a CertificateCancelNotFound with default headers values
func NewCertificateCancelNotFound() *CertificateCancelNotFound {
	return &CertificateCancelNotFound{}
}

/* CertificateCancelNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CertificateCancelNotFound struct {
	models.HyperionErrorReponse
}

// NewCertificateCancelConflict creates a CertificateCancelConflict with default headers values
func NewCertificateCancelConflict() *CertificateCancelConflict {
	return &CertificateCancelConflict{}
}

/* CertificateCancelConflict describes a response with status code 409, with default header values.

Conflict
*/
type CertificateCancelConflict struct {
	models.HyperionErrorReponse
}
