// Copyright 2022 Edgecast Inc., Licensed under the terms of the Apache 2.0
// license. See LICENSE file in project root for terms.

package certificate

// This file was generated by codegen-sdk-go.
// Any changes made to this file may be overwritten.

import (
	"github.com/EdgeCast/ec-sdk-go/edgecast/cps/models"
)

// NewCertificatePutRenewalNoContent creates a CertificatePutRenewalNoContent with default headers values
func NewCertificatePutRenewalNoContent() *CertificatePutRenewalNoContent {
	return &CertificatePutRenewalNoContent{}
}

/* CertificatePutRenewalNoContent describes a response with status code 204, with default header values.

Success
*/
type CertificatePutRenewalNoContent struct {
}

// NewCertificatePutRenewalBadRequest creates a CertificatePutRenewalBadRequest with default headers values
func NewCertificatePutRenewalBadRequest() *CertificatePutRenewalBadRequest {
	return &CertificatePutRenewalBadRequest{}
}

/* CertificatePutRenewalBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CertificatePutRenewalBadRequest struct {
	models.HyperionErrorReponse
}

// NewCertificatePutRenewalNotFound creates a CertificatePutRenewalNotFound with default headers values
func NewCertificatePutRenewalNotFound() *CertificatePutRenewalNotFound {
	return &CertificatePutRenewalNotFound{}
}

/* CertificatePutRenewalNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CertificatePutRenewalNotFound struct {
	models.HyperionErrorReponse
}
