// Copyright 2022 Edgecast Inc., Licensed under the terms of the Apache 2.0
// license. See LICENSE file in project root for terms.

package certificate

// This file was generated by codegen-sdk-go.
// Any changes made to this file may be overwritten.

import (
	"github.com/EdgeCast/ec-sdk-go/edgecast/cps/models"
)

// NewCertificatePatchOK creates a CertificatePatchOK with default headers values
func NewCertificatePatchOK() *CertificatePatchOK {
	return &CertificatePatchOK{}
}

/* CertificatePatchOK describes a response with status code 200, with default header values.

Success
*/
type CertificatePatchOK struct {
	models.CertificateRequestBase
}

// NewCertificatePatchBadRequest creates a CertificatePatchBadRequest with default headers values
func NewCertificatePatchBadRequest() *CertificatePatchBadRequest {
	return &CertificatePatchBadRequest{}
}

/* CertificatePatchBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CertificatePatchBadRequest struct {
	models.HyperionErrorReponse
}

// NewCertificatePatchNotFound creates a CertificatePatchNotFound with default headers values
func NewCertificatePatchNotFound() *CertificatePatchNotFound {
	return &CertificatePatchNotFound{}
}

/* CertificatePatchNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CertificatePatchNotFound struct {
	models.HyperionErrorReponse
}
