// Copyright 2022 Edgecast Inc., Licensed under the terms of the Apache 2.0
// license. See LICENSE file in project root for terms.

package certificate

// This file was generated by codegen-sdk-go.
// Any changes made to this file may be overwritten.

import (
	"github.com/EdgeCast/ec-sdk-go/edgecast/cps/models"
)

// NewCertificatePutRetriggerNoContent creates a CertificatePutRetriggerNoContent with default headers values
func NewCertificatePutRetriggerNoContent() *CertificatePutRetriggerNoContent {
	return &CertificatePutRetriggerNoContent{}
}

/* CertificatePutRetriggerNoContent describes a response with status code 204, with default header values.

Success
*/
type CertificatePutRetriggerNoContent struct {
}

// NewCertificatePutRetriggerBadRequest creates a CertificatePutRetriggerBadRequest with default headers values
func NewCertificatePutRetriggerBadRequest() *CertificatePutRetriggerBadRequest {
	return &CertificatePutRetriggerBadRequest{}
}

/* CertificatePutRetriggerBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CertificatePutRetriggerBadRequest struct {
	models.HyperionErrorReponse
}

// NewCertificatePutRetriggerNotFound creates a CertificatePutRetriggerNotFound with default headers values
func NewCertificatePutRetriggerNotFound() *CertificatePutRetriggerNotFound {
	return &CertificatePutRetriggerNotFound{}
}

/* CertificatePutRetriggerNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CertificatePutRetriggerNotFound struct {
	models.HyperionErrorReponse
}
