// Copyright 2022 Edgecast Inc., Licensed under the terms of the Apache 2.0
// license. See LICENSE file in project root for terms.

package certificate

// This file was generated by codegen-sdk-go.
// Any changes made to this file may be overwritten.

// NewCertificateFindOK creates a CertificateFindOK with default headers values
func NewCertificateFindOK() *CertificateFindOK {
	return &CertificateFindOK{}
}

/* CertificateFindOK describes a response with status code 200, with default header values.

Success
*/
type CertificateFindOK struct {
}
