// Copyright 2022 Edgecast Inc., Licensed under the terms of the Apache 2.0
// license. See LICENSE file in project root for terms.

package certificate

import "github.com/EdgeCast/ec-sdk-go/edgecast/cps/models"

// This file was generated by codegen-sdk-go.
// Any changes made to this file may be overwritten.

// NewCertificateGetRequestNotificationsOK creates a CertificateGetRequestNotificationsOK with default headers values
func NewCertificateGetRequestNotificationsOK() *CertificateGetRequestNotificationsOK {
	return &CertificateGetRequestNotificationsOK{}
}

/*
	CertificateGetRequestNotificationsOK describes a response with status code 200, with default header values.

Success
*/
type CertificateGetRequestNotificationsOK struct {
	models.HyperionCollectionEmailNotification
}

// NewCertificateGetRequestNotificationsBadRequest creates a CertificateGetRequestNotificationsBadRequest with default headers values
func NewCertificateGetRequestNotificationsBadRequest() *CertificateGetRequestNotificationsBadRequest {
	return &CertificateGetRequestNotificationsBadRequest{}
}

/*
	CertificateGetRequestNotificationsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CertificateGetRequestNotificationsBadRequest struct {
	models.HyperionErrorReponse
}

// NewCertificateGetRequestNotificationsNotFound creates a CertificateGetRequestNotificationsNotFound with default headers values
func NewCertificateGetRequestNotificationsNotFound() *CertificateGetRequestNotificationsNotFound {
	return &CertificateGetRequestNotificationsNotFound{}
}

/*
	CertificateGetRequestNotificationsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CertificateGetRequestNotificationsNotFound struct {
	models.HyperionErrorReponse
}
