// Code generated by go-swagger; DO NOT EDIT.

package profiles_waf

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/EdgeCast/ec-sdk-go/rtldmodels"
)

// ProfilesWafUpdateCustomerSettingReader is a Reader for the ProfilesWafUpdateCustomerSetting structure.
type ProfilesWafUpdateCustomerSettingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProfilesWafUpdateCustomerSettingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProfilesWafUpdateCustomerSettingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewProfilesWafUpdateCustomerSettingOK creates a ProfilesWafUpdateCustomerSettingOK with default headers values
func NewProfilesWafUpdateCustomerSettingOK() *ProfilesWafUpdateCustomerSettingOK {
	return &ProfilesWafUpdateCustomerSettingOK{}
}

/* ProfilesWafUpdateCustomerSettingOK describes a response with status code 200, with default header values.

Success
*/
type ProfilesWafUpdateCustomerSettingOK struct {
	Payload *rtldmodels.WafProfileDto
}

func (o *ProfilesWafUpdateCustomerSettingOK) Error() string {
	return fmt.Sprintf("[PUT /v1.0/waf/profiles/{id}][%d] profilesWafUpdateCustomerSettingOK  %+v", 200, o.Payload)
}
func (o *ProfilesWafUpdateCustomerSettingOK) GetPayload() *rtldmodels.WafProfileDto {
	return o.Payload
}

func (o *ProfilesWafUpdateCustomerSettingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rtldmodels.WafProfileDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
