// Copyright 2021 Edgecast Inc., Licensed under the terms of the Apache 2.0 license. See LICENSE file in project root for terms.

package profiles_waf

// This file was generated by codegen-sdk-go.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"

	"github.com/EdgeCast/ec-sdk-go/rtldmodels"
)

// NewProfilesWafUpdateCustomerSettingParams creates a new ProfilesWafUpdateCustomerSettingParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewProfilesWafUpdateCustomerSettingParams() *ProfilesWafUpdateCustomerSettingParams {
	return &ProfilesWafUpdateCustomerSettingParams{}
}

/* ProfilesWafUpdateCustomerSettingParams contains all the parameters to send to the API endpoint
   for the profiles waf update customer setting operation.

   Typically these are written to a http.Request.
*/
type ProfilesWafUpdateCustomerSettingParams struct {

	// Body.
	Body *rtldmodels.WafProfileDto

	// ID.
	//
	// Format: int32
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the profiles waf update customer setting params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProfilesWafUpdateCustomerSettingParams) WithDefaults() *ProfilesWafUpdateCustomerSettingParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the profiles waf update customer setting params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProfilesWafUpdateCustomerSettingParams) SetDefaults() {
	// no default values defined for this parameter
}

// WriteToRequest extracts parameters and sets for the request to be consumed
func WriteToRequestProfilesWafUpdateCustomerSettingParams(o *ProfilesWafUpdateCustomerSettingParams) (RequestParameters, error) {

	var res []error

	params := NewRequestParameters()
	if o.Body != nil {
		params.Body = o.Body
	}

	// path param id
	params.PathParams["id"] = swag.FormatInt32(o.ID)

	if len(res) > 0 {
		return *params, errors.CompositeValidationError(res...)
	}
	return *params, nil
}
