// Code generated by go-swagger; DO NOT EDIT.

package profiles_waf

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/EdgeCast/ec-sdk-go/edgecast/rtldmodels"
)

// ProfilesWafGetCustomerSettingsByIDReader is a Reader for the ProfilesWafGetCustomerSettingsByID structure.
type ProfilesWafGetCustomerSettingsByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProfilesWafGetCustomerSettingsByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProfilesWafGetCustomerSettingsByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewProfilesWafGetCustomerSettingsByIDOK creates a ProfilesWafGetCustomerSettingsByIDOK with default headers values
func NewProfilesWafGetCustomerSettingsByIDOK() *ProfilesWafGetCustomerSettingsByIDOK {
	return &ProfilesWafGetCustomerSettingsByIDOK{}
}

/* ProfilesWafGetCustomerSettingsByIDOK describes a response with status code 200, with default header values.

Success
*/
type ProfilesWafGetCustomerSettingsByIDOK struct {
	Payload *rtldmodels.WafProfileDto
}

func (o *ProfilesWafGetCustomerSettingsByIDOK) Error() string {
	return fmt.Sprintf("[GET /v1.0/waf/profiles/{id}][%d] profilesWafGetCustomerSettingsByIdOK  %+v", 200, o.Payload)
}
func (o *ProfilesWafGetCustomerSettingsByIDOK) GetPayload() *rtldmodels.WafProfileDto {
	return o.Payload
}

func (o *ProfilesWafGetCustomerSettingsByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rtldmodels.WafProfileDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
