// Copyright 2022 Edgecast Inc., Licensed under the terms of the Apache 2.0
// license. See LICENSE file in project root for terms.

package dcv

import "github.com/EdgeCast/ec-sdk-go/edgecast/cps/models"

// This file was generated by codegen-sdk-go.
// Any changes made to this file may be overwritten.

// NewDcvRegenerateDcvTokensOK creates a DcvRegenerateDcvTokensOK with default headers values
func NewDcvRegenerateDcvTokensOK() *DcvRegenerateDcvTokensOK {
	return &DcvRegenerateDcvTokensOK{}
}

/*
	DcvRegenerateDcvTokensOK describes a response with status code 200, with default header values.

Success
*/
type DcvRegenerateDcvTokensOK struct {
	models.HyperionCollectionDomainDcvToken
}

// NewDcvRegenerateDcvTokensBadRequest creates a DcvRegenerateDcvTokensBadRequest with default headers values
func NewDcvRegenerateDcvTokensBadRequest() *DcvRegenerateDcvTokensBadRequest {
	return &DcvRegenerateDcvTokensBadRequest{}
}

/*
	DcvRegenerateDcvTokensBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DcvRegenerateDcvTokensBadRequest struct {
	models.HyperionErrorReponse
}

// NewDcvRegenerateDcvTokensNotFound creates a DcvRegenerateDcvTokensNotFound with default headers values
func NewDcvRegenerateDcvTokensNotFound() *DcvRegenerateDcvTokensNotFound {
	return &DcvRegenerateDcvTokensNotFound{}
}

/*
	DcvRegenerateDcvTokensNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DcvRegenerateDcvTokensNotFound struct {
	models.HyperionErrorReponse
}
