// Code generated by the Code Generation Kit (CGK) using OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
//
// Copyright 2022 Edgecast Inc., Licensed under the terms of the Apache 2.0
// license. See LICENSE file in project root for terms.

/*
Customer Origins API v3

List of API of config Customer Origin.

API version: 0.5.0
Contact: portals-streaming@edgecast.com
*/

package originv3

import (
	"encoding/json"
)

// CustomerOriginGroupADNRequest
type CustomerOriginGroupADNRequest struct {
	Name       string         `json:"name"`
	HostHeader NullableString `json:"host_header,omitempty"`
	// Validation Path
	ValidationPath       string         `json:"validation_path"`
	NetworkTypeId        NullableInt32  `json:"network_type_id,omitempty"`
	Gateway              GatewayRequest `json:"gateway"`
	TlsSettings          *TlsSettings   `json:"tls_settings,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomerOriginGroupADNRequest CustomerOriginGroupADNRequest

// NewCustomerOriginGroupADNRequest instantiates a new CustomerOriginGroupADNRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerOriginGroupADNRequest(name string, validationPath string, gateway GatewayRequest) *CustomerOriginGroupADNRequest {
	this := CustomerOriginGroupADNRequest{}
	this.Name = name
	var hostHeader string = ""
	this.HostHeader = NewNullableString(hostHeader)
	this.ValidationPath = validationPath
	var networkTypeId int32 = 1
	this.NetworkTypeId = NewNullableInt32(networkTypeId)
	this.Gateway = gateway
	return &this
}

// NewCustomerOriginGroupADNRequestWithDefaults instantiates a new CustomerOriginGroupADNRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerOriginGroupADNRequestWithDefaults() *CustomerOriginGroupADNRequest {
	this := CustomerOriginGroupADNRequest{}
	var hostHeader string = ""
	this.HostHeader = NewNullableString(hostHeader)
	var networkTypeId int32 = 1
	this.NetworkTypeId = NewNullableInt32(networkTypeId)
	return &this
}

// GetName returns the Name field value
func (o *CustomerOriginGroupADNRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CustomerOriginGroupADNRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CustomerOriginGroupADNRequest) SetName(v string) {
	o.Name = v
}

// GetHostHeader returns the HostHeader field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerOriginGroupADNRequest) GetHostHeader() string {
	if o == nil || o.HostHeader.Get() == nil {
		var ret string
		return ret
	}
	return *o.HostHeader.Get()
}

// GetHostHeaderOk returns a tuple with the HostHeader field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerOriginGroupADNRequest) GetHostHeaderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HostHeader.Get(), o.HostHeader.IsSet()
}

// HasHostHeader returns a boolean if a field has been set.
func (o *CustomerOriginGroupADNRequest) HasHostHeader() bool {
	if o != nil && o.HostHeader.IsSet() {
		return true
	}

	return false
}

// SetHostHeader gets a reference to the given NullableString and assigns it to the HostHeader field.
func (o *CustomerOriginGroupADNRequest) SetHostHeader(v string) {
	o.HostHeader.Set(&v)
}

// SetHostHeaderNil sets the value for HostHeader to be an explicit nil
func (o *CustomerOriginGroupADNRequest) SetHostHeaderNil() {
	o.HostHeader.Set(nil)
}

// UnsetHostHeader ensures that no value is present for HostHeader, not even an explicit nil
func (o *CustomerOriginGroupADNRequest) UnsetHostHeader() {
	o.HostHeader.Unset()
}

// GetValidationPath returns the ValidationPath field value
func (o *CustomerOriginGroupADNRequest) GetValidationPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ValidationPath
}

// GetValidationPathOk returns a tuple with the ValidationPath field value
// and a boolean to check if the value has been set.
func (o *CustomerOriginGroupADNRequest) GetValidationPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidationPath, true
}

// SetValidationPath sets field value
func (o *CustomerOriginGroupADNRequest) SetValidationPath(v string) {
	o.ValidationPath = v
}

// GetNetworkTypeId returns the NetworkTypeId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerOriginGroupADNRequest) GetNetworkTypeId() int32 {
	if o == nil || o.NetworkTypeId.Get() == nil {
		var ret int32
		return ret
	}
	return *o.NetworkTypeId.Get()
}

// GetNetworkTypeIdOk returns a tuple with the NetworkTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerOriginGroupADNRequest) GetNetworkTypeIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.NetworkTypeId.Get(), o.NetworkTypeId.IsSet()
}

// HasNetworkTypeId returns a boolean if a field has been set.
func (o *CustomerOriginGroupADNRequest) HasNetworkTypeId() bool {
	if o != nil && o.NetworkTypeId.IsSet() {
		return true
	}

	return false
}

// SetNetworkTypeId gets a reference to the given NullableInt32 and assigns it to the NetworkTypeId field.
func (o *CustomerOriginGroupADNRequest) SetNetworkTypeId(v int32) {
	o.NetworkTypeId.Set(&v)
}

// SetNetworkTypeIdNil sets the value for NetworkTypeId to be an explicit nil
func (o *CustomerOriginGroupADNRequest) SetNetworkTypeIdNil() {
	o.NetworkTypeId.Set(nil)
}

// UnsetNetworkTypeId ensures that no value is present for NetworkTypeId, not even an explicit nil
func (o *CustomerOriginGroupADNRequest) UnsetNetworkTypeId() {
	o.NetworkTypeId.Unset()
}

// GetGateway returns the Gateway field value
func (o *CustomerOriginGroupADNRequest) GetGateway() GatewayRequest {
	if o == nil {
		var ret GatewayRequest
		return ret
	}

	return o.Gateway
}

// GetGatewayOk returns a tuple with the Gateway field value
// and a boolean to check if the value has been set.
func (o *CustomerOriginGroupADNRequest) GetGatewayOk() (*GatewayRequest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gateway, true
}

// SetGateway sets field value
func (o *CustomerOriginGroupADNRequest) SetGateway(v GatewayRequest) {
	o.Gateway = v
}

// GetTlsSettings returns the TlsSettings field value if set, zero value otherwise.
func (o *CustomerOriginGroupADNRequest) GetTlsSettings() TlsSettings {
	if o == nil || o.TlsSettings == nil {
		var ret TlsSettings
		return ret
	}
	return *o.TlsSettings
}

// GetTlsSettingsOk returns a tuple with the TlsSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerOriginGroupADNRequest) GetTlsSettingsOk() (*TlsSettings, bool) {
	if o == nil || o.TlsSettings == nil {
		return nil, false
	}
	return o.TlsSettings, true
}

// HasTlsSettings returns a boolean if a field has been set.
func (o *CustomerOriginGroupADNRequest) HasTlsSettings() bool {
	if o != nil && o.TlsSettings != nil {
		return true
	}

	return false
}

// SetTlsSettings gets a reference to the given TlsSettings and assigns it to the TlsSettings field.
func (o *CustomerOriginGroupADNRequest) SetTlsSettings(v TlsSettings) {
	o.TlsSettings = &v
}

func (o CustomerOriginGroupADNRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.HostHeader.IsSet() {
		toSerialize["host_header"] = o.HostHeader.Get()
	}
	if true {
		toSerialize["validation_path"] = o.ValidationPath
	}
	if o.NetworkTypeId.IsSet() {
		toSerialize["network_type_id"] = o.NetworkTypeId.Get()
	}
	if true {
		toSerialize["gateway"] = o.Gateway
	}
	if o.TlsSettings != nil {
		toSerialize["tls_settings"] = o.TlsSettings
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *CustomerOriginGroupADNRequest) UnmarshalJSON(bytes []byte) (err error) {
	varCustomerOriginGroupADNRequest := _CustomerOriginGroupADNRequest{}

	if err = json.Unmarshal(bytes, &varCustomerOriginGroupADNRequest); err == nil {
		*o = CustomerOriginGroupADNRequest(varCustomerOriginGroupADNRequest)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "host_header")
		delete(additionalProperties, "validation_path")
		delete(additionalProperties, "network_type_id")
		delete(additionalProperties, "gateway")
		delete(additionalProperties, "tls_settings")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomerOriginGroupADNRequest struct {
	value *CustomerOriginGroupADNRequest
	isSet bool
}

func (v NullableCustomerOriginGroupADNRequest) Get() *CustomerOriginGroupADNRequest {
	return v.value
}

func (v *NullableCustomerOriginGroupADNRequest) Set(val *CustomerOriginGroupADNRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerOriginGroupADNRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerOriginGroupADNRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerOriginGroupADNRequest(val CustomerOriginGroupADNRequest) NullableCustomerOriginGroupADNRequest {
	return NullableCustomerOriginGroupADNRequest{value: &val, isSet: true}
}

func (v NullableCustomerOriginGroupADNRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerOriginGroupADNRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
