// Code generated by the Code Generation Kit (CGK) using OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
//
// Copyright 2022 Edgecast Inc., Licensed under the terms of the Apache 2.0
// license. See LICENSE file in project root for terms.

/*
Customer Origins API v3

List of API of config Customer Origin.

API version: 0.5.0
Contact: portals-streaming@edgecast.com
*/

package originv3

import (
	"encoding/json"
)

// CustomerOrigin struct for CustomerOrigin
type CustomerOrigin struct {
	Name string `json:"name"`
	// Require if origin_hostname_protocol_type = 1 | 2
	Port                 *float32        `json:"port,omitempty"`
	IsPrimary            bool            `json:"is_primary"`
	OriginShieldRegionId NullableFloat32 `json:"origin_shield_region_id,omitempty"`
	GroupId              *int32          `json:"group_id,omitempty"`
	CloudStorage         *CloudStorage   `json:"cloud_storage,omitempty"`
	StorageTypeId        NullableInt32   `json:"storage_type_id"`
	ProtocolTypeId       NullableInt32   `json:"protocol_type_id"`
	AdditionalProperties map[string]interface{}
}

type _CustomerOrigin CustomerOrigin

// NewCustomerOrigin instantiates a new CustomerOrigin object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerOrigin(name string, isPrimary bool, storageTypeId NullableInt32, protocolTypeId NullableInt32) *CustomerOrigin {
	this := CustomerOrigin{}
	this.Name = name
	this.IsPrimary = isPrimary
	this.StorageTypeId = storageTypeId
	this.ProtocolTypeId = protocolTypeId
	return &this
}

// NewCustomerOriginWithDefaults instantiates a new CustomerOrigin object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerOriginWithDefaults() *CustomerOrigin {
	this := CustomerOrigin{}
	var isPrimary bool = false
	this.IsPrimary = isPrimary
	return &this
}

// GetName returns the Name field value
func (o *CustomerOrigin) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CustomerOrigin) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CustomerOrigin) SetName(v string) {
	o.Name = v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *CustomerOrigin) GetPort() float32 {
	if o == nil || o.Port == nil {
		var ret float32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerOrigin) GetPortOk() (*float32, bool) {
	if o == nil || o.Port == nil {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *CustomerOrigin) HasPort() bool {
	if o != nil && o.Port != nil {
		return true
	}

	return false
}

// SetPort gets a reference to the given float32 and assigns it to the Port field.
func (o *CustomerOrigin) SetPort(v float32) {
	o.Port = &v
}

// GetIsPrimary returns the IsPrimary field value
func (o *CustomerOrigin) GetIsPrimary() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsPrimary
}

// GetIsPrimaryOk returns a tuple with the IsPrimary field value
// and a boolean to check if the value has been set.
func (o *CustomerOrigin) GetIsPrimaryOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPrimary, true
}

// SetIsPrimary sets field value
func (o *CustomerOrigin) SetIsPrimary(v bool) {
	o.IsPrimary = v
}

// GetOriginShieldRegionId returns the OriginShieldRegionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerOrigin) GetOriginShieldRegionId() float32 {
	if o == nil || o.OriginShieldRegionId.Get() == nil {
		var ret float32
		return ret
	}
	return *o.OriginShieldRegionId.Get()
}

// GetOriginShieldRegionIdOk returns a tuple with the OriginShieldRegionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerOrigin) GetOriginShieldRegionIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.OriginShieldRegionId.Get(), o.OriginShieldRegionId.IsSet()
}

// HasOriginShieldRegionId returns a boolean if a field has been set.
func (o *CustomerOrigin) HasOriginShieldRegionId() bool {
	if o != nil && o.OriginShieldRegionId.IsSet() {
		return true
	}

	return false
}

// SetOriginShieldRegionId gets a reference to the given NullableFloat32 and assigns it to the OriginShieldRegionId field.
func (o *CustomerOrigin) SetOriginShieldRegionId(v float32) {
	o.OriginShieldRegionId.Set(&v)
}

// SetOriginShieldRegionIdNil sets the value for OriginShieldRegionId to be an explicit nil
func (o *CustomerOrigin) SetOriginShieldRegionIdNil() {
	o.OriginShieldRegionId.Set(nil)
}

// UnsetOriginShieldRegionId ensures that no value is present for OriginShieldRegionId, not even an explicit nil
func (o *CustomerOrigin) UnsetOriginShieldRegionId() {
	o.OriginShieldRegionId.Unset()
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *CustomerOrigin) GetGroupId() int32 {
	if o == nil || o.GroupId == nil {
		var ret int32
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerOrigin) GetGroupIdOk() (*int32, bool) {
	if o == nil || o.GroupId == nil {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *CustomerOrigin) HasGroupId() bool {
	if o != nil && o.GroupId != nil {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given int32 and assigns it to the GroupId field.
func (o *CustomerOrigin) SetGroupId(v int32) {
	o.GroupId = &v
}

// GetCloudStorage returns the CloudStorage field value if set, zero value otherwise.
func (o *CustomerOrigin) GetCloudStorage() CloudStorage {
	if o == nil || o.CloudStorage == nil {
		var ret CloudStorage
		return ret
	}
	return *o.CloudStorage
}

// GetCloudStorageOk returns a tuple with the CloudStorage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerOrigin) GetCloudStorageOk() (*CloudStorage, bool) {
	if o == nil || o.CloudStorage == nil {
		return nil, false
	}
	return o.CloudStorage, true
}

// HasCloudStorage returns a boolean if a field has been set.
func (o *CustomerOrigin) HasCloudStorage() bool {
	if o != nil && o.CloudStorage != nil {
		return true
	}

	return false
}

// SetCloudStorage gets a reference to the given CloudStorage and assigns it to the CloudStorage field.
func (o *CustomerOrigin) SetCloudStorage(v CloudStorage) {
	o.CloudStorage = &v
}

// GetStorageTypeId returns the StorageTypeId field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *CustomerOrigin) GetStorageTypeId() int32 {
	if o == nil || o.StorageTypeId.Get() == nil {
		var ret int32
		return ret
	}

	return *o.StorageTypeId.Get()
}

// GetStorageTypeIdOk returns a tuple with the StorageTypeId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerOrigin) GetStorageTypeIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.StorageTypeId.Get(), o.StorageTypeId.IsSet()
}

// SetStorageTypeId sets field value
func (o *CustomerOrigin) SetStorageTypeId(v int32) {
	o.StorageTypeId.Set(&v)
}

// GetProtocolTypeId returns the ProtocolTypeId field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *CustomerOrigin) GetProtocolTypeId() int32 {
	if o == nil || o.ProtocolTypeId.Get() == nil {
		var ret int32
		return ret
	}

	return *o.ProtocolTypeId.Get()
}

// GetProtocolTypeIdOk returns a tuple with the ProtocolTypeId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerOrigin) GetProtocolTypeIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProtocolTypeId.Get(), o.ProtocolTypeId.IsSet()
}

// SetProtocolTypeId sets field value
func (o *CustomerOrigin) SetProtocolTypeId(v int32) {
	o.ProtocolTypeId.Set(&v)
}

func (o CustomerOrigin) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Port != nil {
		toSerialize["port"] = o.Port
	}
	if true {
		toSerialize["is_primary"] = o.IsPrimary
	}
	if o.OriginShieldRegionId.IsSet() {
		toSerialize["origin_shield_region_id"] = o.OriginShieldRegionId.Get()
	}
	if o.GroupId != nil {
		toSerialize["group_id"] = o.GroupId
	}
	if o.CloudStorage != nil {
		toSerialize["cloud_storage"] = o.CloudStorage
	}
	if true {
		toSerialize["storage_type_id"] = o.StorageTypeId.Get()
	}
	if true {
		toSerialize["protocol_type_id"] = o.ProtocolTypeId.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *CustomerOrigin) UnmarshalJSON(bytes []byte) (err error) {
	varCustomerOrigin := _CustomerOrigin{}

	if err = json.Unmarshal(bytes, &varCustomerOrigin); err == nil {
		*o = CustomerOrigin(varCustomerOrigin)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "port")
		delete(additionalProperties, "is_primary")
		delete(additionalProperties, "origin_shield_region_id")
		delete(additionalProperties, "group_id")
		delete(additionalProperties, "cloud_storage")
		delete(additionalProperties, "storage_type_id")
		delete(additionalProperties, "protocol_type_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomerOrigin struct {
	value *CustomerOrigin
	isSet bool
}

func (v NullableCustomerOrigin) Get() *CustomerOrigin {
	return v.value
}

func (v *NullableCustomerOrigin) Set(val *CustomerOrigin) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerOrigin) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerOrigin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerOrigin(val *CustomerOrigin) *NullableCustomerOrigin {
	return &NullableCustomerOrigin{value: val, isSet: true}
}

func (v NullableCustomerOrigin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerOrigin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
