// Code generated by the Code Generation Kit (CGK) using OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
//
// Copyright 2022 Edgecast Inc., Licensed under the terms of the Apache 2.0
// license. See LICENSE file in project root for terms.

/*
Customer Origins API v3

List of API of config Customer Origin.

API version: 0.5.0
Contact: portals-streaming@edgecast.com
*/

package originv3

import (
	"encoding/json"
)

// ProtocolType struct for ProtocolType
type ProtocolType struct {
	Id                   *int32  `json:"id,omitempty"`
	Name                 *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProtocolType ProtocolType

// NewProtocolType instantiates a new ProtocolType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProtocolType() *ProtocolType {
	this := ProtocolType{}
	return &this
}

// NewProtocolTypeWithDefaults instantiates a new ProtocolType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProtocolTypeWithDefaults() *ProtocolType {
	this := ProtocolType{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProtocolType) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtocolType) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProtocolType) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ProtocolType) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProtocolType) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtocolType) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProtocolType) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProtocolType) SetName(v string) {
	o.Name = &v
}

func (o ProtocolType) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *ProtocolType) UnmarshalJSON(bytes []byte) (err error) {
	varProtocolType := _ProtocolType{}

	if err = json.Unmarshal(bytes, &varProtocolType); err == nil {
		*o = ProtocolType(varProtocolType)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProtocolType struct {
	value *ProtocolType
	isSet bool
}

func (v NullableProtocolType) Get() *ProtocolType {
	return v.value
}

func (v *NullableProtocolType) Set(val *ProtocolType) {
	v.value = val
	v.isSet = true
}

func (v NullableProtocolType) IsSet() bool {
	return v.isSet
}

func (v *NullableProtocolType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProtocolType(val ProtocolType) NullableProtocolType {
	return NullableProtocolType{value: &val, isSet: true}
}

func (v NullableProtocolType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProtocolType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
