// Code generated by go-swagger; DO NOT EDIT.

package lookups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/EdgeCast/ec-sdk-go/edgecast/rtldmodels"
)

// LookupsGetFieldsCdnReader is a Reader for the LookupsGetFieldsCdn structure.
type LookupsGetFieldsCdnReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LookupsGetFieldsCdnReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLookupsGetFieldsCdnOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLookupsGetFieldsCdnOK creates a LookupsGetFieldsCdnOK with default headers values
func NewLookupsGetFieldsCdnOK() *LookupsGetFieldsCdnOK {
	return &LookupsGetFieldsCdnOK{}
}

/* LookupsGetFieldsCdnOK describes a response with status code 200, with default header values.

Success
*/
type LookupsGetFieldsCdnOK struct {
	Payload *rtldmodels.HyperionCollectionLogFieldDto
}

func (o *LookupsGetFieldsCdnOK) Error() string {
	return fmt.Sprintf("[GET /v1.0/cdn/fields][%d] lookupsGetFieldsCdnOK  %+v", 200, o.Payload)
}
func (o *LookupsGetFieldsCdnOK) GetPayload() *rtldmodels.HyperionCollectionLogFieldDto {
	return o.Payload
}

func (o *LookupsGetFieldsCdnOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rtldmodels.HyperionCollectionLogFieldDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
