// Code generated by go-swagger; DO NOT EDIT.

package lookups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/EdgeCast/ec-sdk-go/edgecast/rtldmodels"
)

// LookupsGetDownsamplingRatesReader is a Reader for the LookupsGetDownsamplingRates structure.
type LookupsGetDownsamplingRatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LookupsGetDownsamplingRatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLookupsGetDownsamplingRatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewLookupsGetDownsamplingRatesOK creates a LookupsGetDownsamplingRatesOK with default headers values
func NewLookupsGetDownsamplingRatesOK() *LookupsGetDownsamplingRatesOK {
	return &LookupsGetDownsamplingRatesOK{}
}

/* LookupsGetDownsamplingRatesOK describes a response with status code 200, with default header values.

Success
*/
type LookupsGetDownsamplingRatesOK struct {
	Payload *rtldmodels.HyperionCollectionSystemDouble
}

func (o *LookupsGetDownsamplingRatesOK) Error() string {
	return fmt.Sprintf("[GET /v1.0/downsampling-rates][%d] lookupsGetDownsamplingRatesOK  %+v", 200, o.Payload)
}
func (o *LookupsGetDownsamplingRatesOK) GetPayload() *rtldmodels.HyperionCollectionSystemDouble {
	return o.Payload
}

func (o *LookupsGetDownsamplingRatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rtldmodels.HyperionCollectionSystemDouble)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
