// Copyright 2022 Edgecast Inc., Licensed under the terms of the Apache 2.0
// license. See LICENSE file in project root for terms.

package organization

// This file was generated by codegen-sdk-go.
// Any changes made to this file may be overwritten.

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
)

// NewOrganizationFindParams creates a new OrganizationFindParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOrganizationFindParams() OrganizationFindParams {
	return OrganizationFindParams{}
}

// OrganizationFindParams contains all the parameters to send to the API
// endpoint for the organization find operation. Typically these are written
// to a http.Request.
type OrganizationFindParams struct {

	// Name.
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the organization find params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrganizationFindParams) WithDefaults() *OrganizationFindParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the organization find params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OrganizationFindParams) SetDefaults() {
	// no default values defined for this parameter
}

// WriteToRequest extracts parameters and sets for the request to be consumed
func WriteToRequestOrganizationFindParams(o OrganizationFindParams) (RequestParameters, error) {

	var res []error

	params := NewRequestParameters()

	// path param name
	params.PathParams["name"] = o.Name

	if len(res) > 0 {
		return *params, errors.CompositeValidationError(res...)
	}
	return *params, nil
}
