// Copyright 2022 Edgecast Inc., Licensed under the terms of the Apache 2.0
// license. See LICENSE file in project root for terms.

package organization

// This file was generated by codegen-sdk-go.
// Any changes made to this file may be overwritten.

import (
	"github.com/EdgeCast/ec-sdk-go/edgecast/cps/models"
)

// NewOrganizationFindOK creates a OrganizationFindOK with default headers values
func NewOrganizationFindOK() *OrganizationFindOK {
	return &OrganizationFindOK{}
}

/* OrganizationFindOK describes a response with status code 200, with default header values.

Success
*/
type OrganizationFindOK struct {
	models.HyperionCollectionOrganizationDetailDto
}

// NewOrganizationFindBadRequest creates a OrganizationFindBadRequest with default headers values
func NewOrganizationFindBadRequest() *OrganizationFindBadRequest {
	return &OrganizationFindBadRequest{}
}

/* OrganizationFindBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type OrganizationFindBadRequest struct {
	models.HyperionErrorReponse
}
