// Copyright 2022 Edgecast Inc., Licensed under the terms of the Apache 2.0
// license. See LICENSE file in project root for terms.

package task

import "github.com/EdgeCast/ec-sdk-go/edgecast/cps/models"

// This file was generated by codegen-sdk-go.
// Any changes made to this file may be overwritten.

// NewTaskGetOK creates a TaskGetOK with default headers values
func NewTaskGetOK() *TaskGetOK {
	return &TaskGetOK{}
}

/*
	TaskGetOK describes a response with status code 200, with default header values.

Success
*/
type TaskGetOK struct {
	models.TaskItem
}

// NewTaskGetBadRequest creates a TaskGetBadRequest with default headers values
func NewTaskGetBadRequest() *TaskGetBadRequest {
	return &TaskGetBadRequest{}
}

/*
	TaskGetBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type TaskGetBadRequest struct {
	models.HyperionErrorReponse
}

// NewTaskGetNotFound creates a TaskGetNotFound with default headers values
func NewTaskGetNotFound() *TaskGetNotFound {
	return &TaskGetNotFound{}
}

/*
	TaskGetNotFound describes a response with status code 404, with default header values.

Not Found
*/
type TaskGetNotFound struct {
	models.HyperionErrorReponse
}
