// Copyright 2022 Edgecast Inc., Licensed under the terms of the Apache 2.0
// license. See LICENSE file in project root for terms.

package task

// This file was generated by codegen-sdk-go.
// Any changes made to this file may be overwritten.

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
)

// NewTaskGetByStatusParams creates a new TaskGetByStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewTaskGetByStatusParams() TaskGetByStatusParams {
	return TaskGetByStatusParams{}
}

// TaskGetByStatusParams contains all the parameters to send to the API
// endpoint for the task get by status operation. Typically these are written
// to a http.Request.
type TaskGetByStatusParams struct {

	// Status.
	Status *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the task get by status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TaskGetByStatusParams) WithDefaults() *TaskGetByStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the task get by status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *TaskGetByStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WriteToRequest extracts parameters and sets for the request to be consumed
func WriteToRequestTaskGetByStatusParams(o TaskGetByStatusParams) (RequestParameters, error) {

	var res []error

	params := NewRequestParameters()

	if o.Status != nil {

		// query param status
		var qrStatus string

		if o.Status != nil {
			qrStatus = *o.Status
		}
		qStatus := qrStatus
		if qStatus != "" {

			params.QueryParams["status"] = qStatus
		}
	}

	if len(res) > 0 {
		return *params, errors.CompositeValidationError(res...)
	}
	return *params, nil
}
