// Code generated by go-swagger; DO NOT EDIT.

package profiles_cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/EdgeCast/ec-sdk-go/rtldmodels"
)

// ProfilesGetCustomerSettingsReader is a Reader for the ProfilesGetCustomerSettings structure.
type ProfilesGetCustomerSettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProfilesGetCustomerSettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProfilesGetCustomerSettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewProfilesGetCustomerSettingsOK creates a ProfilesGetCustomerSettingsOK with default headers values
func NewProfilesGetCustomerSettingsOK() *ProfilesGetCustomerSettingsOK {
	return &ProfilesGetCustomerSettingsOK{}
}

/* ProfilesGetCustomerSettingsOK describes a response with status code 200, with default header values.

Success
*/
type ProfilesGetCustomerSettingsOK struct {
	Payload *rtldmodels.HyperionCollectionCdnProfileDto
}

func (o *ProfilesGetCustomerSettingsOK) Error() string {
	return fmt.Sprintf("[GET /v1.0/cdn/profiles][%d] profilesGetCustomerSettingsOK  %+v", 200, o.Payload)
}
func (o *ProfilesGetCustomerSettingsOK) GetPayload() *rtldmodels.HyperionCollectionCdnProfileDto {
	return o.Payload
}

func (o *ProfilesGetCustomerSettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rtldmodels.HyperionCollectionCdnProfileDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
