// Copyright 2022 Edgecast Inc., Licensed under the terms of the Apache 2.0
// license. See LICENSE file in project root for terms.

package customer

// This file was generated by codegen-sdk-go.
// Any changes made to this file may be overwritten.

import (
	"github.com/EdgeCast/ec-sdk-go/edgecast/cps/models"
)

// NewCustomerGetCustomerNotificationsOK creates a CustomerGetCustomerNotificationsOK with default headers values
func NewCustomerGetCustomerNotificationsOK() *CustomerGetCustomerNotificationsOK {
	return &CustomerGetCustomerNotificationsOK{}
}

/* CustomerGetCustomerNotificationsOK describes a response with status code 200, with default header values.

Success
*/
type CustomerGetCustomerNotificationsOK struct {
	models.HyperionCollectionEmailNotification
}

// NewCustomerGetCustomerNotificationsNotFound creates a CustomerGetCustomerNotificationsNotFound with default headers values
func NewCustomerGetCustomerNotificationsNotFound() *CustomerGetCustomerNotificationsNotFound {
	return &CustomerGetCustomerNotificationsNotFound{}
}

/* CustomerGetCustomerNotificationsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CustomerGetCustomerNotificationsNotFound struct {
	models.HyperionErrorReponse
}
