// Copyright 2022 Edgecast Inc., Licensed under the terms of the Apache 2.0
// license. See LICENSE file in project root for terms.

package customer

// This file was generated by codegen-sdk-go.
// Any changes made to this file may be overwritten.

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
)

// NewCustomerGetCustomerNotificationsParams creates a new CustomerGetCustomerNotificationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCustomerGetCustomerNotificationsParams() CustomerGetCustomerNotificationsParams {
	return CustomerGetCustomerNotificationsParams{}
}

// CustomerGetCustomerNotificationsParams contains all the parameters to send to the API
// endpoint for the customer get customer notifications operation. Typically these are written
// to a http.Request.
type CustomerGetCustomerNotificationsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the customer get customer notifications params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerGetCustomerNotificationsParams) WithDefaults() *CustomerGetCustomerNotificationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the customer get customer notifications params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CustomerGetCustomerNotificationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WriteToRequest extracts parameters and sets for the request to be consumed
func WriteToRequestCustomerGetCustomerNotificationsParams(o CustomerGetCustomerNotificationsParams) (RequestParameters, error) {

	var res []error

	params := NewRequestParameters()

	if len(res) > 0 {
		return *params, errors.CompositeValidationError(res...)
	}
	return *params, nil
}
