// Copyright 2021 Edgecast Inc., Licensed under the terms of the Apache 2.0 license. See LICENSE file in project root for terms.

package profiles_cdn

// This file was generated by codegen-sdk-go.
// Editing this file might prove futile when you re-run the swagger generate command

// NewProfilesDeleteCustomerSettingsByIDNoContent creates a ProfilesDeleteCustomerSettingsByIDNoContent with default headers values
func NewProfilesDeleteCustomerSettingsByIDNoContent() *ProfilesDeleteCustomerSettingsByIDNoContent {
	return &ProfilesDeleteCustomerSettingsByIDNoContent{}
}

/* ProfilesDeleteCustomerSettingsByIDNoContent describes a response with status code 204, with default header values.

Success
*/
type ProfilesDeleteCustomerSettingsByIDNoContent struct {
}
