// Code generated by go-swagger; DO NOT EDIT.

package profiles_cdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/EdgeCast/ec-sdk-go/edgecast/rtldmodels"
)

// ProfilesUpdateCustomerSettingReader is a Reader for the ProfilesUpdateCustomerSetting structure.
type ProfilesUpdateCustomerSettingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProfilesUpdateCustomerSettingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProfilesUpdateCustomerSettingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewProfilesUpdateCustomerSettingOK creates a ProfilesUpdateCustomerSettingOK with default headers values
func NewProfilesUpdateCustomerSettingOK() *ProfilesUpdateCustomerSettingOK {
	return &ProfilesUpdateCustomerSettingOK{}
}

/* ProfilesUpdateCustomerSettingOK describes a response with status code 200, with default header values.

Success
*/
type ProfilesUpdateCustomerSettingOK struct {
	Payload *rtldmodels.CdnProfileDto
}

func (o *ProfilesUpdateCustomerSettingOK) Error() string {
	return fmt.Sprintf("[PUT /v1.0/cdn/profiles/{id}][%d] profilesUpdateCustomerSettingOK  %+v", 200, o.Payload)
}
func (o *ProfilesUpdateCustomerSettingOK) GetPayload() *rtldmodels.CdnProfileDto {
	return o.Payload
}

func (o *ProfilesUpdateCustomerSettingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rtldmodels.CdnProfileDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
