// Copyright 2021 Edgecast Inc., Licensed under the terms of the Apache 2.0 license. See LICENSE file in project root for terms.

package profiles_cdn

// This file was generated by codegen-sdk-go.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
)

// NewProfilesGetCustomerSettingsParams creates a new ProfilesGetCustomerSettingsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewProfilesGetCustomerSettingsParams() *ProfilesGetCustomerSettingsParams {
	return &ProfilesGetCustomerSettingsParams{}
}

/* ProfilesGetCustomerSettingsParams contains all the parameters to send to the API endpoint
   for the profiles get customer settings operation.

   Typically these are written to a http.Request.
*/
type ProfilesGetCustomerSettingsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the profiles get customer settings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProfilesGetCustomerSettingsParams) WithDefaults() *ProfilesGetCustomerSettingsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the profiles get customer settings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProfilesGetCustomerSettingsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WriteToRequest extracts parameters and sets for the request to be consumed
func WriteToRequestProfilesGetCustomerSettingsParams(o *ProfilesGetCustomerSettingsParams) (RequestParameters, error) {

	var res []error

	params := NewRequestParameters()

	if len(res) > 0 {
		return *params, errors.CompositeValidationError(res...)
	}
	return *params, nil
}
